### ISSUE TITLE
Running into link errors on Windows

### ISSUE THREAD

**Issue by cybergeek94** [rust-gnome/glib#11]
After fixing a bunch of configuration-related compiler errors, I was presented with this:

```
note: C:\users\austin\Rust\gdk\target\debug\deps\libglib-fcaf29643d8f5d21.rlib(glib-fcaf29643d8f5d21.o): In function `glib::permission::Permission::get_allowed':
C:\msys64\home\Austin\.cargo\git\checkouts\glib-27833b4b6d67ca46\master\src/permission.rs:27: undefined reference to `g_permission_get_allowed'
C:\users\austin\Rust\gdk\target\debug\deps\libglib-fcaf29643d8f5d21.rlib(glib-fcaf29643d8f5d21.o): In function `glib::permission::Permission::get_can_acquire':
C:\msys64\home\Austin\.cargo\git\checkouts\glib-27833b4b6d67ca46\master\src/permission.rs:34: undefined reference to `g_permission_get_can_acquire'
C:\users\austin\Rust\gdk\target\debug\deps\libglib-fcaf29643d8f5d21.rlib(glib-fcaf29643d8f5d21.o): In function `glib::permission::Permission::get_can_release':
C:\msys64\home\Austin\.cargo\git\checkouts\glib-27833b4b6d67ca46\master\src/permission.rs:41: undefined reference to `g_permission_get_can_release'
C:\users\austin\Rust\gdk\target\debug\deps\libglib-fcaf29643d8f5d21.rlib(glib-fcaf29643d8f5d21.o): In function `glib::permission::Permission::impl_update':
C:\msys64\home\Austin\.cargo\git\checkouts\glib-27833b4b6d67ca46\master\src/permission.rs:48: undefined reference to `g_permission_impl_update'
C:\users\austin\Rust\gdk\target\debug\deps\libglib-fcaf29643d8f5d21.rlib(glib-fcaf29643d8f5d21.o): In function `glib::value::Value::new':
C:\msys64\home\Austin\.cargo\git\checkouts\glib-27833b4b6d67ca46\master\src/value.rs:36: undefined reference to `create_gvalue'
```

The `g_permission` functions are defined by the GIO library, a separate lib and link unit on Windows. And then `create_gvalue()` is an internal function not exported in the GLib headers, at least for me.

This is with the latest Windows x64 release of GTK from [here][1].

Possible solutions:

* Move the `g_permission` functions to a `gio-sys` crate that links to `-lgio-2`
* Use `g_value_init()` instead of `create_gvalue()`

[1]: http://www.gtk.org/download/win64.php

**Comment by GuillaumeGomez** [comment]
Erf... I don't develop under Windows so I can't help you on that... Just make a PR with your preferred solution (or maybe someone else has an idea on how to resolve this ?).

**Comment by gkoz** [comment]
The `gio` problem we could plug by asking to link to `gio` in the `gtk-sys` build script.

**Comment by GuillaumeGomez** [comment]
I'm just thinking that we could split out gio from glib. It would seem more logical since we split out every library.

**Comment by gkoz** [comment]
It seems there's very little substance to `gio` right now and it's unlikely to grow soon.

**Comment by GuillaumeGomez** [comment]
Yep but it'll certainly grow. By splitting it out of glib, we avoid any potential problem like that in the future.

**Comment by gkoz** [comment]
I'm not sure I understand what kind of problem that would be. `glib` comes bundled with `gio`, `gmodule`, `gobject` and `gthread` on my system and there's little reason to pretend that they're usable separately.

**Comment by GuillaumeGomez** [comment]
Hum, I didn't saw that... Then yes, let's just ask to link to `gio` in the `glib-sys` build script like you proposed @gkoz.

**Comment by gkoz** [comment]
https://github.com/rust-gnome/glib/pull/12 should fix the `gio` problem.

**Comment by GuillaumeGomez** [comment]
I merged it. Can you confirm it's fixed now @cybergeek94 ?

**Comment by gkoz** [comment]
I'm working on fixing the `GValue`.

**Comment by cybergeek94** [comment]
The `g_permission` functions are fixed for me now. Just `create_gvalue()` is left.

**Comment by gkoz** [comment]
That would be https://github.com/rust-gnome/glib/pull/13 and https://github.com/rust-gnome/gtk/pull/35

**Comment by GuillaumeGomez** [comment]
And they're both merged.

**Comment by cybergeek94** [comment]
Link errors are fixed on my end. Good job!
