### ISSUE TITLE
Will not work on 1.0

### ISSUE THREAD

**Issue by Eilie** [rust-gnome/glib#20]
Can't build it with beta because of `#![feature(alloc)]` and they don't plan to make `alloc` stable in 1.0 either.

**Comment by Eilie** [comment]
THIS IS IMPORTANT

**Comment by GuillaumeGomez** [comment]
@gkoz: Didn't you replace `Box` by `RefCell` ?

**Comment by gkoz** [comment]
In the signals modules I've taken advantage of some unstable functions from `std::boxed` that need to be replaced with `transmute` for 1.0... Some other minor stuff might be incompatible as well. I'll get down to fixing that stuff soon™.
We may need to either start running travis builds on both beta and nightly, or just the former.

**Comment by GuillaumeGomez** [comment]
Until the 1.0 release comes out, we'll only build for nightly. After, I'm thinking about creating a branch which will tracks the nightly (the mast will be on the release).

**Comment by gkoz** [comment]
Imagine someone makes everything compatible with 1.0 today. After that there's a risk of any PR breaking that because the submitter and the tests had only built on nightly. It's because of not considering 1.0 soon enough that I introduced some uses of unstable features that I'll have to clean up now =)

**Comment by GuillaumeGomez** [comment]
Yes, sorry for that... I didn't want to start tracking the beta too soon. Maybe it was an error in the end.

**Comment by gkoz** [comment]
That's a useful lesson in release engineering for us haha

**Comment by GuillaumeGomez** [comment]
I totally agree. Next time, I'll create a branch which will track the release a lot more soon.

**Comment by gkoz** [comment]
Well, there's always an option of just staying conservative and not chasing nightlies. Because having multiple branches is probably more work and it's not like we're in dire need of the freshest Rust features.

**Comment by GuillaumeGomez** [comment]
Yes, but I like having the choice between using the last up to date version (the nightly) and the stable one. The master would only be for fix, whereas the nightly is for adding new features and stuff. And time to time, we transfer nightly code to "stable" code.

**Comment by gkoz** [comment]
Alright. But it's usually the master that is the bleeding edge and some number of more stable branches get backports from it.

**Comment by GuillaumeGomez** [comment]
Oh right, I never remember in which way it works...

**Comment by jashephe** [comment]
Would there be an advantage to switching to beta compatibility now and using a feature gate as in [hyper](https://github.com/hyperium/hyper/search?utf8=%E2%9C%93&q=feature+nightly&type=Code)?  That would prepare us for the possibility of adding features that only work on nightly, while still allowing most of everything to work with beta.

**Comment by GuillaumeGomez** [comment]
@jashephe: We're talking about that with @gkoz. We'll come back to you very soon.

The doc isn't a priority for the moment, for now, those who really need it, just use `cargo build`.

**Comment by gkoz** [comment]
Turns out, `feature(alloc)` was the only blocker for this.

**Comment by GuillaumeGomez** [comment]
@Eilie: So it will be beta compatible the time PRs are merged.

**Comment by Eilie** [comment]
@GuillaumeGomez, @gkoz Works now, thank you guys!
