### ISSUE TITLE
Add getting the error message from a GError

### ISSUE THREAD

**Issue by gsingh93** [rust-gnome/glib#48]
I don't think there's a way to get the message from a GError in safe code right now. I need to add this and add a Debug implementation for `glib::Error` so I can use it in a `Result`.

I can implement a `message() -> &str` function to access the field, if that's all that needs to be done.

**Comment by GuillaumeGomez** [comment]
`message() -> &str` seems good for me.

**Comment by gkoz** [comment]
It should probably implement all of `Debug`, `Display` and `Error`.
