### ISSUE TITLE
Dependency on glib-macros failing on mac travis builds

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-gnome/glib#726]
When I updated my dependencies from:
* gtk 0.8
* glib 0.9.0

to 
* gtk 0.9
* glib 0.10.x

The mac [travis builds](https://travis-ci.org/github/andrewdavidmackenzie/gtk-rs-state/jobs/749247926) of my lib [`gtk-rs-state`](https://github.com/andrewdavidmackenzie/gtk-rs-state/) have started failing:

```
   Compiling gtk-rs-state v0.4.0 (/Users/travis/build/andrewdavidmackenzie/gtk-rs-state)

error[E0463]: can't find crate for `glib_macros` which `glib` depends on
```

It seems that the dependency on `glib-macros` was added to glib between 0.9.0 and 0.10.0
The builds continue to pass just fine on linux.

Is there a way I can update to gtk 0.9, glib 0.10.x and have them build OK on Mac?

**Comment by sdroege** [comment]
Why doesn't it find `glib-macros` for you? That definitely exists https://crates.io/crates/glib-macros and it's even in your `Cargo.lock`.

If I understand you correctly this only happens on macOS but the same works fine elsewhere?

**Comment by andrewdavidmackenzie** [comment]
This is weird. It seems to be related to travis caching.
I have caching of cargo on.
I deleted all caches, and then repeated a build that failed and now it passes!

Will investigate more, but this maybe a red herring so don't waste time on it.

**Comment by sdroege** [comment]
I had similar issues with cargo caching on gitlab CI. It also doesn't seem to reduce build times much, so I just disabled it :)

Let's close this one here for now then. If you have any new insights, please let me know!

**Comment by andrewdavidmackenzie** [comment]
Yep, removing caches and it works. No idea. Closing.
