### ISSUE TITLE
Connect internals

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-gnome/glib#9]
As I am running into issues with the current implementation of `Connect` (cfr. rust-gnome/gtk#30), I am looking at the implementation to see if I can pin-point the origin of my issues. However, within [that code](https://github.com/rust-gnome/glib/blob/master/src/traits.rs#L68) you can find:

```
ffi::glue_signal_connect(
                self.unwrap_gobject(),
                signal_name.borrow_to_glib().0,
                Some(trampoline),
                user_data_ptr
            );
```

Which can also be found [among the FFI defintions](https://github.com/rust-gnome/glib/blob/master/glib-sys/src/lib.rs#L210):

```
    pub fn glue_signal_connect(g_object: *mut C_GObject,
                               signal: *const c_char,
                               func: Option<extern "C" fn()>,
                               user_data: *const c_void);
```

What exactly is `glue_signal_connect`? I'm asking because I can't seem to find this in Glib.

~~Furthermore, the `Signal` trait seems to have a `fetch_cb` method. What should this be used for? As I don't see it being used (directly) at the moment.~~ (They are used to create the trampolines).

**Comment by gkoz** [comment]
This glue function lives in `gtk_glue.c`. I can't say there's much point to having this glue function. The problems with closures have been discussed here: https://github.com/jeremyletang/rgtk/issues/28

**Comment by GuillaumeGomez** [comment]
@jeremyletang will explain this better than me.

**Comment by gkoz** [comment]
I believe this question has been resolved in the process of the signals reform.

**Comment by GuillaumeGomez** [comment]
I think too. I close it.
